### ISSUE TITLE
Doens not compiles anymore in 2022

### ISSUE THREAD

**Issue by ewidance** [fab672000/MIDIUSB_1x1#3]
Hi. Tried to compile on Arduino 1.8.19 with Midi Library 5.0.2 and MIDIUSB 1.0.5 but lt unfortunately fails. 

```
Arduino\libraries\MIDI_Library\src/MIDI.hpp:75:5: error: no matching function for call to 'HardwareSerial::begin()'
     mTransport.begin();
     ^~~~~~~~~~
```

It seems macro MIDIBRIDGE_CREATE_INSTANCE(Type, SerialPort, Name)  MidiBridge<Type> is not anymore adapted to recent midi and midisub evolutions.
